version: '3.9'
services:
  minio:
    image: minio/minio
    command: server --address ":443" /data
    ports:
      - "9000:9000"
      - "9001:9001"
      - "443:443"
    environment:
      MINIO_ROOT_USER: "luanxu"
      MINIO_ROOT_PASSWORD: "luanxu"
      MINIO_ACCESS_KEY: "testtest"
      MINIO_SECRET_KEY: "testtest"
    volumes:
      - ./minio/data:/data
      - ./minio/.minio:/root/.minio
  mysql:
    image: mysql:latest
    container_name: s-mysql
    command: --default-authentication-plugin=mysql_native_password
    init: true
    restart: always
    platform: "linux/amd64"
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=blockpay
      - MYSQL_USER=blockpay_dev
      - MYSQL_PASSWORD=lvxm9Fk6dldt%Wji
    volumes:
      - ./mysql/data:/var/lib/mysql
  redis:
    image: redis:latest
    restart: "always"
    container_name: s-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper/zookeeper/data:/bitnami/zookeeper
  zookeeper2:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper/zookeeper2/data:/bitnami/zookeeper
  zookeeper3:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper/zookeeper3/data:/bitnami/zookeeper
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    links:
      - zookeeper
      - zookeeper2
      - zookeeper3
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${MASTERHOST}:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - ./kafka/kafka1/data:/bitnami/kafka
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3
  kafka2:
    image: 'bitnami/kafka:latest'
    ports:
      - "9093:9093"
    links:
      - zookeeper
      - zookeeper2
      - zookeeper3
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${MASTERHOST}:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - ./kafka/kafka2/data:/bitnami/kafka
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3
  kafka3:
    image: 'bitnami/kafka:latest'
    ports:
      - "9094:9094"
    links:
      - zookeeper
      - zookeeper2
      - zookeeper3
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${MASTERHOST}:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
    - ./kafka/kafka3/data:/bitnami/kafka
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3