version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: s-mysql
    command: --default-authentication-plugin=mysql_native_password
    init: true
    restart: always
    platform: "linux/amd64"
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=blockpay
      - MYSQL_USER=blockpay_dev
      - MYSQL_PASSWORD=lvxm9Fk6dldt%Wji
    volumes:
      - ./mysql/data:/var/lib/mysql
    

  redis:
    image: redis:latest
    restart: "always"
    container_name: s-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: s-zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper/data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.1
    container_name: s-kafka
    ports:
      - "9092:9092"
    volumes:
      - "./kafka/data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
    